openapi: "3.0.0"
info:
  title: Swagger Petstore - OpenAPI 3.0
  version: 1.0.1
paths:
  /foo/{name}:
    get:
      x-openapi-router-controller: src.FooView
      operationId: getdata
      responses:
        200:
          description: Sucesso
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string